channel: TextChannel {
    type: 'text',
    deleted: false,
    id: '325477729589919744',
    name: 'bot-test',
    rawPosition: 3,
    parentID: undefined,
    permissionOverwrites: Collection [Map] {},
    topic: null,
    lastMessageID: '775896482439233546',
    rateLimitPerUser: 0,
    lastPinTimestamp: null,
    guild: Guild {
      members: [GuildMemberManager],
      channels: [GuildChannelManager],
      roles: [RoleManager],
      presences: [PresenceManager],
      voiceStates: [VoiceStateManager],
      deleted: false,
      available: true,
      id: '168905955457761281',
      shardID: 0,
      name: 'TheKrypt',
      icon: '0c69fa5d0a5f1b9971277264ed270458',
      splash: null,
      discoverySplash: null,
      region: 'us-south',
      memberCount: 8,
      large: false,
      features: [],
      applicationID: null,
      afkTimeout: 900,
      afkChannelID: null,
      systemChannelID: null,
      embedEnabled: undefined,
      premiumTier: 0,
      premiumSubscriptionCount: 0,
      verificationLevel: 'NONE',
      explicitContentFilter: 'DISABLED',
      mfaLevel: 0,
      joinedTimestamp: 1567252227557,
      defaultMessageNotifications: 'ALL',
      systemChannelFlags: [SystemChannelFlags],
      maximumMembers: 100000,
      vanityURLCode: null,
      vanityURLUses: null,
      description: null,
      banner: null,
      rulesChannelID: null,
      publicUpdatesChannelID: null,
      preferredLocale: 'en-US',
      ownerID: '151105775681536000',
      emojis: [GuildEmojiManager]
    },
    messages: MessageManager {
      cacheType: [class LimitedCollection extends Collection],
      cache: [LimitedCollection [Map]],
      channel: [Circular]
    },
    nsfw: false,
    _typing: Map {}
  },
  deleted: false,
  id: '775896482439233546',
  type: 'DEFAULT',
  system: false,
  content: '1',
  author: User {
    id: '151105775681536000',
    username: 'Kryosoul',
    bot: false,
    discriminator: '1173',
    avatar: 'ea251b6f067bd4589f3318af30bd8f90',
    flags: UserFlags { bitfield: 0 },
    lastMessageID: '775896482439233546',
    lastMessageChannelID: '325477729589919744'
  },
  pinned: false,
  tts: false,
  nonce: '775896525971652608',
  embeds: [],
  attachments: Collection [Map] {},
  createdTimestamp: 1605058536873,
  editedTimestamp: 0,
  reactions: ReactionManager {
    cacheType: [class Collection extends Collection],
    cache: Collection [Map] {},
    message: [Circular]
  },
  mentions: MessageMentions {
    everyone: false,
    users: Collection [Map] {},
    roles: Collection [Map] {},
    _members: null,
    _channels: null,
    crosspostedChannels: Collection [Map] {}
  },
  webhookID: null,
  application: null,
  activity: null,
  _edits: [],
  flags: MessageFlags { bitfield: 0 },
  reference: null
}
